language: php
php:
- '5.6'

env:
- DLM_PACKAGE_VERSION=1.2.$TRAVIS_BUILD_NUMBER

install:
- php bin/composer.phar install -n

script:
- vendor/bin/phing -f build.xml prepare.version release

deploy:
  provider: releases
  api_key:
    secure: JCxHp3gPAEMsZ8TaM0B3p+W2WRWAmpY95X6aPnbUu1dgbEvhVyOstbexAZdW0pD0XY6+XU8777mEkW7MiY1JkX2bjwNZjzHebFqD5EXxn6trS3ojt4Y4jd/cUBWC4zfSgRkGOTwURU4z1OxuybyhDXe7f1V99LKrLDajCKGILLgIBDfoTzfmUZkfXFoR3VVXOvLIrjHpflakfCtkCTto5aTrrKQtytIkyk3WJtI/lt946R94zQxGy3qmi5iTIgV4T2+Kgao9SX7wsHucYEHs/B9XKKMxt3LzF5ovRhtDTNselsA613ZWce9xgCZZbM7S5QbK8vriXy/LE9gMneCrJtgLtTF3qrVU3lJkvhE2Z/yDmMm0GPHw0XXYh59cwrv51pPMb6a6a7WXaVSa3wLZiuSlAbe1OI8dzQbqghMOmodK+L7ysTasdt64qMDr3oG8K8bAc001YrysiS5/nPVYGCtDk0k3BpxA5TwBFa+z5fdGOcuh3cmyEUkR/qgOMv8vYhMbiYTwfaF3dbmY//SALa3r6bOM+v95tY4M5I0AhRNljWYbT/Xus2X/aM40t6oFVjkcVpw883kJIcojMPITu4VvpH4PBgNS/SI0ZRY4EZsJpnbmNaLbpgPGbZgdoSK8kTiS13PRoSAoes9U9QTTuuzttg1pkJJBW4l5olvpt6k=
  file_glob: true
  file: tmp/out/bin/*
  skip_cleanup: true
  on:
    tags: true